name: CMake Build and Test

on:
  push:
    branches: [ master, test_claude_code ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.3
      
    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v1.14
      with:
        cmake-version: '3.14.x'
        
    - name: Configure CMake
      run: cmake -B build -G "Visual Studio 17 2022" -A x64
      
    - name: Build
      run: cmake --build build --config Debug
      
    - name: Run Tests
      run: ctest --test-dir build -C Debug --output-on-failure --verbose
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          build/Testing/
          build/**/*.exe
        retention-days: 30